/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1edd_201504242;

import Cola.Cola;
import ListaCircular.ListaCircular;
import ListaSimple.ListaSimple;
import java.util.HashSet;
import java.util.Random;

/**
 *
 * @author p_ab1
 */
public class Jugadores extends javax.swing.JFrame {
//public char letras[]= new char[7];
public ListaSimple listaLetras = new ListaSimple();
public Cola colaLetras = new Cola();
public ListaCircular jugadores=new ListaCircular();
public Cola randomCola = new Cola ();
    /**
     * Creates new form Jugadores
     */
    public Jugadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Nuevo Jugador");

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ir al Juego");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        randomLetras();
        System.out.println("Letras ingresadas a Lista Simple");
        for(int i =0;i<letras.length;i++){
            listaLetras.agregar(String.valueOf(letras[i]));
            System.out.print(letras[i]+" ");
        }        
        jugadores.insertarUltimo(caja.getText(),listaLetras);
        System.out.println("Cantidad de nodos:"+jugadores.getSize());
        jugadores.imprimir(); 
        caja.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

public void randomLetras(){
    ListaSimple ly = new ListaSimple();
    ly.agregar(new Letras("A", 12, 1));
    ly.agregar(new Letras("E", 12, 1));
    ly.agregar(new Letras("O",9, 1));
    ly.agregar(new Letras("I", 6, 1));
    ly.agregar(new Letras("N", 5, 1));
    ly.agregar(new Letras("L", 4, 1));
    ly.agregar(new Letras("R", 5, 1));
    ly.agregar(new Letras("U", 5, 1));
    ly.agregar(new Letras("T", 4, 1));
    ly.agregar(new Letras("D", 5, 2));
    ly.agregar(new Letras("G", 2, 2));
    ly.agregar(new Letras("C", 4, 3));
    ly.agregar(new Letras("B", 2,3));
    ly.agregar(new Letras("M", 2, 3));
    ly.agregar(new Letras("P", 2, 3));
    ly.agregar(new Letras("H", 2, 4));
    ly.agregar(new Letras("F", 1, 4));
    ly.agregar(new Letras("V", 1,4));
    ly.agregar(new Letras("Y", 1,4));
    ly.agregar(new Letras("Q", 1, 5));
    ly.agregar(new Letras("J", 1, 8));
    ly.agregar(new Letras("ñ", 1, 8));
    ly.agregar(new Letras("X", 1, 8));
    ly.agregar(new Letras("Z", 1, 10));
    
    Random random = new Random();
       
        while(randomCola.getSize()<85){
            int x = (int)(random.nextDouble() * 23.0);
            Letras f;
            f=(Letras)ly.getValor(x);
                if(f.getCantidad()>0){
                randomCola.agregar(f.getLetra());
                System.out.print(f.getLetra()+" ");
                f.setCantidad(f.getCantidad()-1);            
            }       
        }
        System.out.print("SALIO");
    
        char[] letra={'A','B','C','D','E','F','G','H','I','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
           
           Random rnd = new Random();
           int x;
            for (int i = 0; i < 7; i++) {
                    x = (int)(rnd.nextDouble() * 10.0);
                    letras[i]=(letra[x]);
            }
        }
}

